# data exploration with pandas

## preamble

make it easier to see wider tables

In [63]:
# imports
import sqlite3
import pandas as pd

# make the cell wider in HTML mode
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>")) 

# larger width for plain-text output
pd.set_option('display.width', 250)
# rest of the imports

## load database tables

In [64]:

pd.set_option('display.width', 250) # Set to a large number

# Create a SQL connection to our SQLite database
con = sqlite3.connect("database.db")

cur = con.cursor()

machine_log = pd.read_sql_query("SELECT * from machine_log", con)
maintenance = pd.read_sql_query("SELECT * from maintenance", con)
shift_schedule = pd.read_sql_query("SELECT * from shift_schedule", con)


# Be sure to close the connection
con.close()

## explore the data

### machine_log table

In [65]:
machine_log.head(25)

                             employee_ID                            machine_ID              Time_in             Time_out
0   5ccedc77-3429-479c-acda-4ccb01f35efe  32b55d35-e676-46f1-84c6-9290764b5018  2024-12-02T06:28:00  2024-12-02T12:23:22
1   9fb932d4-f039-4722-96ff-82e389e3995a  bf5cb443-292a-48f3-b713-b4c7ebb7344d  2024-12-02T06:26:00  2024-12-02T09:12:12
2   9fb932d4-f039-4722-96ff-82e389e3995a  14b062ae-88c8-4ad1-aee1-f220fd547512  2024-12-02T14:12:00  2024-12-02T19:07:47
3   5ccedc77-3429-479c-acda-4ccb01f35efe  0d2329d9-fa09-4a46-b673-89669b02a56d  2024-12-02T14:11:00  2024-12-02T17:21:47
4   9fb932d4-f039-4722-96ff-82e389e3995a  f3d2273a-3740-4227-a10f-4d0c5b86c0ef  2024-12-02T22:19:00  2024-12-03T01:33:14
5   9fb932d4-f039-4722-96ff-82e389e3995a  32b55d35-e676-46f1-84c6-9290764b5018  2024-12-03T01:49:14  2024-12-03T05:16:19
6   cae8c077-3779-45b3-96a1-da2c9cfbba43  bf5cb443-292a-48f3-b713-b4c7ebb7344d  2024-12-02T22:16:00  2024-12-03T03:36:20
7   5ccedc77-3429-479c-acda-4ccb01f35efe  32b55d35-e676-46f1-84c6-9290764b5018  2024-12-03T06:27:00  2024-12-03T11:47:04
8   ad689cf8-8759-4153-b778-5728f2655b19  14b062ae-88c8-4ad1-aee1-f220fd547512  2024-12-03T06:17:00  2024-12-03T08:58:07
9   cae8c077-3779-45b3-96a1-da2c9cfbba43  80d16aaf-f1a4-4fe5-ad78-dc4bfb9e8dda  2024-12-03T06:10:00  2024-12-03T08:23:01
10  cae8c077-3779-45b3-96a1-da2c9cfbba43  0d2329d9-fa09-4a46-b673-89669b02a56d  2024-12-03T09:02:01  2024-12-03T11:27:26
11  153d3a3f-56bc-49cb-9121-5785d9977338  80d16aaf-f1a4-4fe5-ad78-dc4bfb9e8dda  2024-12-03T22:08:00  2024-12-04T01:03:01
12  ad689cf8-8759-4153-b778-5728f2655b19  ecc2c55e-986d-4842-b114-3591cab5f7c4  2024-12-03T22:13:00  2024-12-04T03:45:43
13  d283eb3a-5fbd-438e-89cf-158de6e96d45  f3d2273a-3740-4227-a10f-4d0c5b86c0ef  2024-12-04T06:22:00  2024-12-04T10:16:26
14  d283eb3a-5fbd-438e-89cf-158de6e96d45  0d2329d9-fa09-4a46-b673-89669b02a56d  2024-12-04T10:44:26  2024-12-04T13:55:00
15  8ed5f036-44f7-48cd-8aeb-34f967124890  ecc2c55e-986d-4842-b114-3591cab5f7c4  2024-12-04T06:13:00  2024-12-04T09:15:27
16  ad689cf8-8759-4153-b778-5728f2655b19  14b062ae-88c8-4ad1-aee1-f220fd547512  2024-12-04T06:30:00  2024-12-04T08:53:33
17  ad689cf8-8759-4153-b778-5728f2655b19  80d16aaf-f1a4-4fe5-ad78-dc4bfb9e8dda  2024-12-04T09:17:33  2024-12-04T12:50:15
18  ad689cf8-8759-4153-b778-5728f2655b19  32b55d35-e676-46f1-84c6-9290764b5018  2024-12-04T22:23:00  2024-12-05T03:34:11
19  50fe3281-7812-4170-967a-34d0c643e653  32b55d35-e676-46f1-84c6-9290764b5018  2024-12-04T22:12:00  2024-12-05T02:26:24
20  50fe3281-7812-4170-967a-34d0c643e653  0d2329d9-fa09-4a46-b673-89669b02a56d  2024-12-05T22:23:00  2024-12-06T00:29:20
21  50fe3281-7812-4170-967a-34d0c643e653  f3d2273a-3740-4227-a10f-4d0c5b86c0ef  2024-12-06T00:49:20  2024-12-06T04:25:12
22  5ccedc77-3429-479c-acda-4ccb01f35efe  32b55d35-e676-46f1-84c6-9290764b5018  2024-12-05T22:21:00  2024-12-06T01:18:57
23  d283eb3a-5fbd-438e-89cf-158de6e96d45  32b55d35-e676-46f1-84c6-9290764b5018  2024-12-06T06:15:00  2024-12-06T09:17:19
24  b35331ce-af2e-49dd-87e3-55b26210b784  0d2329d9-fa09-4a46-b673-89669b02a56d  2024-12-06T14:09:00  2024-12-06T16:14:16

In [66]:
machine_log.info()

<class 'pandas.DataFrame'>
RangeIndex: 2100 entries, 0 to 2099
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_ID  2100 non-null   str
 1   machine_ID   2100 non-null   str
 2   Time_in      2100 non-null   str
 3   Time_out     2100 non-null   str
dtypes: str(4)
memory usage: 65.8 KB

In [67]:
machine_log.isna().sum()

employee_ID    0
machine_ID     0
Time_in        0
Time_out       0
dtype: int64

### maintenance table

In [68]:
maintenance.head(25)

    request_timestamp      fix_timestamp                           reason_code                          requestor_ID
0   12/03/24 09:16:07  12/03/24 13:16:07  af11c1e7-7946-4a34-abd2-ed1c05f73dba  ad689cf8-8759-4153-b778-5728f2655b19
1   12/11/24 20:58:33     12/11/24 22:06  af11c1e7-7946-4a34-abd2-ed1c05f73dba  b35331ce-af2e-49dd-87e3-55b26210b784
2      12/19/24 16:50  12/19/24 14:05:00  f0fc795a-5a93-41f6-a058-8857c3881083  8ed5f036-44f7-48cd-8aeb-34f967124890
3   12/24/24 03:48:43  12/24/24 06:01:01  d33bf820-6770-4a78-8ba3-fb8041f089dc  ad689cf8-8759-4153-b778-5728f2655b19
4   01/02/25 22:19:00  01/03/25 02:19:00  618d3f43-0173-445f-9e0d-54254f4f81b0  9974d75b-3338-44fe-a179-0134676b1b69
5   01/06/25 10:23:54  01/06/25 14:07:00  7166a9f5-3620-4dbc-a3f3-760f0e2eb028  50fe3281-7812-4170-967a-34d0c643e653
6   03/21/25 02:50:41     03/21/25 06:06  efca6c3a-14c6-495e-ab45-1936d1d5c42f  8ed5f036-44f7-48cd-8aeb-34f967124890
7   04/01/25 09:55:50  04/01/25 13:55:50  af11c1e7-7946-4a34-abd2-ed1c05f73dba  b8e3c71f-6bf0-4d62-b310-57ca7d411fab
8   04/21/25 09:40:34  04/21/25 09:38:38  0e4a1175-ec15-4269-b9e4-8824b1eb72c8  ad689cf8-8759-4153-b778-5728f2655b19
9   06/20/25 11:50:30     06/20/25 15:50  7166a9f5-3620-4dbc-a3f3-760f0e2eb028  baa1c6f1-404b-4eaf-962a-01dec28753f8
10  07/26/25 02:21:32  07/26/25 02:14:32  618d3f43-0173-445f-9e0d-54254f4f81b0  50fe3281-7812-4170-967a-34d0c643e653
11     08/16/25 02:34     08/16/25 03:51  d33bf820-6770-4a78-8ba3-fb8041f089dc  153d3a3f-56bc-49cb-9121-5785d9977338
12  10/02/25 11:04:37  10/02/25 14:12:00  efca6c3a-14c6-495e-ab45-1936d1d5c42f  ad689cf8-8759-4153-b778-5728f2655b19
13  12/05/24 03:39:11     12/05/24 07:39  7166a9f5-3620-4dbc-a3f3-760f0e2eb028  ad689cf8-8759-4153-b778-5728f2655b19
14  12/06/24 09:40:19                NaN  67c3b9fe-85fd-4dc4-a2c4-d84f5467115b  d283eb3a-5fbd-438e-89cf-158de6e96d45
15  01/22/25 21:23:43  01/22/25 22:46:10  d33bf820-6770-4a78-8ba3-fb8041f089dc  d283eb3a-5fbd-438e-89cf-158de6e96d45
16  01/28/25 01:12:01  01/28/25 01:38:01  af11c1e7-7946-4a34-abd2-ed1c05f73dba  cae8c077-3779-45b3-96a1-da2c9cfbba43
17  01/28/25 03:55:14  01/28/25 06:04:18  efca6c3a-14c6-495e-ab45-1936d1d5c42f  cae8c077-3779-45b3-96a1-da2c9cfbba43
18  01/31/25 12:44:44  01/31/25 16:44:44  af11c1e7-7946-4a34-abd2-ed1c05f73dba  d283eb3a-5fbd-438e-89cf-158de6e96d45
19  02/01/25 03:56:53  02/01/25 01:29:32  67c3b9fe-85fd-4dc4-a2c4-d84f5467115b  9fb932d4-f039-4722-96ff-82e389e3995a
20  02/05/25 19:26:41  02/05/25 18:41:47  7166a9f5-3620-4dbc-a3f3-760f0e2eb028  9974d75b-3338-44fe-a179-0134676b1b69
21  02/06/25 21:12:00     02/07/25 00:32  f94cf6b0-c986-4a9f-a664-718333674334  b8e3c71f-6bf0-4d62-b310-57ca7d411fab
22  02/20/25 10:25:28  02/20/25 14:25:28  af11c1e7-7946-4a34-abd2-ed1c05f73dba  baa1c6f1-404b-4eaf-962a-01dec28753f8
23  02/25/25 21:59:43  02/26/25 00:31:42  f0fc795a-5a93-41f6-a058-8857c3881083  5ccedc77-3429-479c-acda-4ccb01f35efe
24  03/04/25 04:12:54  03/04/25 06:29:00  0e4a1175-ec15-4269-b9e4-8824b1eb72c8  2dd301c8-a91a-4a5c-b623-c4dd26fb984f

In [69]:
maintenance.info()

<class 'pandas.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   request_timestamp  707 non-null    str
 1   fix_timestamp      636 non-null    str
 2   reason_code        707 non-null    str
 3   requestor_ID       707 non-null    str
dtypes: str(4)
memory usage: 22.2 KB

### shift_schedule table

In [70]:
shift_schedule.head(25)

                             employee_ID  shift        date  clock_in clock_out    Title
0   9974d75b-3338-44fe-a179-0134676b1b69      1  12/02/2024   6:15 AM      2:00  Manager
1   5ccedc77-3429-479c-acda-4ccb01f35efe      1  12/02/2024      6:00   2:00 PM     LINE
2   9fb932d4-f039-4722-96ff-82e389e3995a      1  12/02/2024   6:15 AM   2:15 PM     LINE
3   9974d75b-3338-44fe-a179-0134676b1b69      2  12/02/2024   2:00 PM  10:15 PM  Manager
4   9fb932d4-f039-4722-96ff-82e389e3995a      2  12/02/2024   2:00 PM  10:00 PM     Line
5   5ccedc77-3429-479c-acda-4ccb01f35efe      2  12/02/2024   2:05 PM  10:00 PM     LINE
6   221c4e00-3f99-41ee-baf2-7f802dc5fd3d      3  12/02/2024  10:10 PM      6:00  Manager
7   9fb932d4-f039-4722-96ff-82e389e3995a      3  12/02/2024  10:05 PM   6:00 AM     line
8   cae8c077-3779-45b3-96a1-da2c9cfbba43      3  12/02/2024  10:00 PM   6:15 AM     line
9   9974d75b-3338-44fe-a179-0134676b1b69      1  12/03/2024   6:10 AM   2:15 PM  Manager
10  5ccedc77-3429-479c-acda-4ccb01f35efe      1  12/03/2024   6:00 AM   2:00 PM     Line
11  ad689cf8-8759-4153-b778-5728f2655b19      1  12/03/2024   6:00 AM   2:10 PM     Line
12  cae8c077-3779-45b3-96a1-da2c9cfbba43      1  12/03/2024      6:15      2:05     LINE
13  baa1c6f1-404b-4eaf-962a-01dec28753f8      2  12/03/2024   2:10 PM  10:05 PM  Manager
14  baa1c6f1-404b-4eaf-962a-01dec28753f8      3  12/03/2024  10:00 PM      6:15  manager
15  153d3a3f-56bc-49cb-9121-5785d9977338      3  12/03/2024  10:00 PM   6:15 AM     LINE
16  ad689cf8-8759-4153-b778-5728f2655b19      3  12/03/2024     10:15   6:00 AM     Line
17  baa1c6f1-404b-4eaf-962a-01dec28753f8      1  12/04/2024   6:00 AM   2:10 PM  Manager
18  d283eb3a-5fbd-438e-89cf-158de6e96d45      1  12/04/2024   6:00 AM   2:00 PM     LINE
19  8ed5f036-44f7-48cd-8aeb-34f967124890      1  12/04/2024   6:10 AM      2:00     line
20  ad689cf8-8759-4153-b778-5728f2655b19      1  12/04/2024      6:00   2:00 PM     line
21  9974d75b-3338-44fe-a179-0134676b1b69      3  12/04/2024     10:10   6:00 AM  Manager
22  ad689cf8-8759-4153-b778-5728f2655b19      3  12/04/2024  10:00 PM   6:10 AM     line
23  50fe3281-7812-4170-967a-34d0c643e653      3  12/04/2024  10:15 PM   6:15 AM     Line
24  9974d75b-3338-44fe-a179-0134676b1b69      1  12/05/2024      6:00   2:00 PM  Manager

In [71]:
shift_schedule.info()

<class 'pandas.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_ID  2318 non-null   str
 1   shift        2318 non-null   int64
 2   date         2318 non-null   str
 3   clock_in     2318 non-null   str
 4   clock_out    2318 non-null   str
 5   Title        2318 non-null   str
dtypes: int64(1), str(5)
memory usage: 108.8 KB

In [72]:
shift_schedule.Title.value_counts()

Title
line       943
Manager    581
Line       318
LINE       306
manager    170
Name: count, dtype: int64

In [73]:
shift_schedule["shift"].value_counts()

shift
2    801
3    767
1    750
Name: count, dtype: int64

In [74]:
shift_schedule.clock_in.value_counts()

clock_in
2:00 PM     345
10:00 PM    315
6:00 AM     309
2:05 PM     118
10:15 PM    117
10:05 PM    116
6:15 AM     115
2:10 PM     112
2:15 PM     110
6:05 AM     106
10:10 PM    105
6:10 AM     103
6:00         54
2:00         48
10:00        47
2:05         32
10:10        29
6:15         23
10:15        23
6:05         22
2:15         22
6:10         18
10:05        15
2:10         14
Name: count, dtype: int64

In [75]:
shift_schedule.clock_out.value_counts()

clock_out
10:00 PM    334
2:00 PM     313
6:00 AM     307
10:05 PM    128
6:15 AM     125
10:15 PM    119
6:10 AM     115
2:15 PM     109
10:10 PM    108
2:10 PM     106
6:05 AM     103
2:05 PM      99
2:00         70
10:00        58
6:00         55
6:15         25
2:05         20
6:05         19
10:15        19
6:10         18
10:05        18
2:15         17
10:10        17
2:10         16
Name: count, dtype: int64